name: Publish Snapshot (DEV Version)

on:
  push:
    branches: [ master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: europe-west1

jobs:
  publish-samples:
    runs-on: ubuntu-latest
    steps:
      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Update Parameters
        run: |
          sed -i "s|@@branch@@|${GITHUB_REF#refs/heads/}|g" *.xsd
          sed -i "s|@@version@@|SNAPSHOT|g" *.xsd
          sed -i "s|@@commitId@@|${GITHUB_SHA:0:7}|g" *.xsd
      - name: Setup GCloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '298.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Copy files to GCloud Bucket
        run: gsutil cp ./*.xsd  gs://schema.cip4.org/jdfschema_2_x/

      - name: Create ZIP Archive
        run: zip jdfschema_2_x.zip *.xsd

      - name: Copy ZIP Archive to GCloud Bucket
        run: gsutil cp ./*.zip  gs://schema.cip4.org/

      - name: Createa tar.gz Archive
        run: tar -czvf jdfschema_2_x.tar.gz *.xsd

      - name: Copy tar.gz Archive to GCloud Bucket
        run: gsutil cp ./*.tar.gz  gs://schema.cip4.org/

      # Upload artifact
      - name: Upload Document
        uses: actions/upload-artifact@v2
        with:
          name: xsd-artifact
          path: xjdf.xsd
